### ISSUE TITLE
InvalidParameterValueException: runtime no longer supported

### ISSUE THREAD

**Issue by flynnCoolblue** [shoreditch-ops/chaos-lambda#13]
InvalidParameterValueException: The runtime parameter of nodejs is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs4.3) while creating or updating functions.

Node 6.9

Im guessing im not alone here.

**Comment by hassy** [comment]
Thanks @flynnCoolblue That's been fixed now.
