### ISSUE TITLE
Terminate instances by tags

### ISSUE THREAD

**Issue by davinerd** [shoreditch-ops/chaos-lambda#17]
Add support in the Chaosfile.json to terminate instances by tags instead of names (implementing 'simianarmy.chaos.ASGtag.key' and 'simianarmy.chaos.ASGtag.value').

**Comment by ashwgupt** [comment]
Hi @davinerd ,

does this mean, we can leave out the enableForASGs array as empty? As our Lambdas are not part of an ASG, we don't have a value for this param.

**Comment by davinerd** [comment]
You can leave it empty, but bear in mind that if you don't use ASG as parameter to terminate instances, you must use tags.

The `index.js` looks first for ASG, then tags. If you don't specify tags or ASGs, then your instances will not be affected by chaos-lambda.
