### ISSUE TITLE
Add integration with Llama Agent

### ISSUE THREAD

**Issue by hassy** [shoreditch-ops/chaos-lambda#4]
:point_right:  [Llama Agent](https://github.com/hassy/llama-agent)
- [ ] Add support for listing the ASGs for which the instances will have the agent running on them
- [ ] Add support for configuring VPC access

**Comment by darbio** [comment]
Is integration with the agent supported yet?

**Comment by hassy** [comment]
Not yet, just hasn't been a priority for me personally. Any PRs would be happily merged though. :)

**Comment by hassy** [comment]
Not being planned any time soon unfortunately, closing the issue for now.
